[vars]
image = "pipefile/test"

[[steps]]
id = "build"
name = "Build"
vars = { buildMessage = "Built!" }
cmds = [
    # "echo 'Built!'"
    "echo '@{buildMessage}'",
    "docker build -t @{image} ."
]

[[steps]]
id = "parallel_build"
name = "Build 2"
cmds = [
    "echo 'Built!'"
    # "docker build -t pipefile/test ."
]

[[steps]]
id = "test"
name = "Test"
needs = ["build"]
cmds = [
    "echo 'Tested!'"
]

[[steps]]
id = "deploy"
name = "Deploy"
needs = ["test"]
cmds = [
    "echo 'Deployed!'",
    "1/0"
]
