[[steps]]
id = "build"
name = "Build"
cmds = [
    # "echo 'Built!'"
    "docker build -t pipefile/test ."
]


[[steps]]
id = "test"
name = "Test"
needs = ["build"]
cmds = [
    "echo 'Tested!'"
]

[[steps]]
id = "deploy"
name = "Deploy"
needs = ["test"]
cmds = [
    "echo 'Deployed!'"
]
